# Copyright (C) 2024 psionicprjkt

name: build-default

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Android Build Environment
        run: |
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh

      - name: Setup Repository & Resources
        run: |
          git config --global user.name "officialputuid" && git config --global user.email officialputuid@hack.id
          git clone --recursive --depth=1 https://officialputuid:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO_PRIVATE }} -b ${{ secrets.GH_BRANCH_PRIVATE }} mido && cd mido
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Setup Version
        run: |
          cd mido
          v=$(cat version)
          d="arch/arm64/configs/mido_defconfig"
          sed -i 's/CONFIG_KSU=y/CONFIG_KSU=n/' $d
          sed -i 's/\(CONFIG_LOCALVERSION="-psionic-\)kernelsu-\(.*"\)/\1\2/' $d
          sed -i 's/\(CONFIG_LOCALVERSION="-psionic-\).*"/\1'"$v\"/" $d

      - name: Check Version Kernel
        run: |
          cd mido
          kv=$(make kernelversion 2>/dev/null)
          d="arch/arm64/configs/mido_defconfig"
          echo "Kernel Version: $kv"
          echo "Local Version: $(grep CONFIG_LOCALVERSION= $d | cut -d '"' -f2)"

      - name: Setup Build Kernel
        run: cd mido && bash build-default.sh

      - name: Setup ENV
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"
          echo "VERSION_KERNEL=$(cat version)" >> "$GITHUB_ENV"

      - name: Setup Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "Default"
          prerelease: false
          title: psionic-kernel-mido-${{ env.RELEASE_DATE }}-${{ env.VERSION_KERNEL }}
          files: |
            mido/AnyKernel/psionic-kernel-mido*

